/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package finitas.hacia.adelante

fun main() {
  val x = 1
  val h :Array<Double> = arrayOf(0.1, 0.01, 0.001, 0.0001, 0.00001)

  var c = h.size - 1

  MetodoHaciaAdelante(x, h, c)

}

fun MetodoHaciaAdelante(x: Int, h: Array<Double>, c: Int){
  for (i in 0..c){
    val x_h = x + h[i]

    val fx_h = Math.sin(x_h)-2*x_h*x_h

    val fx = Math.sin(x.toDouble())-2*x*x

    val fx_fx_h = fx_h - fx

    val resultado = fx_fx_h / h[i]

    println(resultado)
  }

  val derivada = Math.cos(x.toDouble())-4*x

  println("Este seria el resultado de la derivada de manera analitica: $derivada")

}
